import nbformat as nbf
from pathlib import Path


OUT = Path(__file__).with_name("gemini_table_postprocess_probe.ipynb")


def md(text):
    return nbf.v4.new_markdown_cell(text)


def code(text):
    return nbf.v4.new_code_cell(text)


nb = nbf.v4.new_notebook()
nb["metadata"] = {
    "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
    "language_info": {"name": "python", "pygments_lexer": "ipython3"},
}

nb.cells = [
    md(
        "# Gemini Hybrid Postprocess Probe - Burnaby R1\n\n"
        "Offline-only notebook. It merges already-generated Gemini table and non-table outputs, then runs deterministic normalization, exception splitting, deduplication, and coverage checks.\n\n"
        "No Gemini/API calls are made here."
    ),
    code(
        "import json\n"
        "import os\n"
        "import re\n"
        "from pathlib import Path\n\n"
        "import pandas as pd\n\n"
        "def locate_prototype_dir():\n"
        "    cwd = Path.cwd()\n"
        "    for d in [cwd, *cwd.parents]:\n"
        "        candidate = d / 'code' / 'prototype_pipeline'\n"
        "        if (candidate / 'prototype_rule_extraction_pipeline.ipynb').exists():\n"
        "            return candidate.resolve()\n"
        "        if (d / 'prototype_rule_extraction_pipeline.ipynb').exists():\n"
        "            return d.resolve()\n"
        "    return cwd.resolve()\n\n"
        "PROTOTYPE_DIR = locate_prototype_dir()\n"
        "os.chdir(PROTOTYPE_DIR)\n\n"
        "import sys\n"
        "import importlib\n"
        "if str(PROTOTYPE_DIR) not in sys.path:\n"
        "    sys.path.insert(0, str(PROTOTYPE_DIR))\n"
        "import prototype_target_aware_helpers as helpers\n"
        "importlib.reload(helpers)\n"
        "from prototype_target_aware_helpers import *\n\n"
        "print('PROTOTYPE_DIR:', PROTOTYPE_DIR)"
    ),
    md("## Paths"),
    code(
        "TARGET_CITY = 'burnaby'\n"
        "RUN_ID = f'prototype_{TARGET_CITY}_rule_pipeline'\n"
        "RULE_DIR = PROTOTYPE_DIR / 'outputs' / TARGET_CITY / RUN_ID / '03_rules'\n"
        "TABLE_DIR = PROTOTYPE_DIR / 'outputs' / TARGET_CITY / RUN_ID / '04_gemini_table_probe'\n"
        "NON_TABLE_DIR = PROTOTYPE_DIR / 'outputs' / TARGET_CITY / RUN_ID / '06_gemini_non_table_probe'\n"
        "POST_DIR = PROTOTYPE_DIR / 'outputs' / TARGET_CITY / RUN_ID / '07_gemini_hybrid_postprocess_probe'\n"
        "POST_DIR.mkdir(parents=True, exist_ok=True)\n\n"
        "TABLE_RULES_CSV = TABLE_DIR / 'gemini_table_rules.csv'\n"
        "NON_TABLE_RULES_CSV = NON_TABLE_DIR / 'gemini_non_table_rules_raw.csv'\n"
        "TABLE_BATCHES_JSON = RULE_DIR / 'table_rule_batches.json'\n"
        "EVIDENCE_UNITS_JSON = RULE_DIR / 'evidence_units.json'\n\n"
        "for label, path in [('table rules', TABLE_RULES_CSV), ('non-table rules', NON_TABLE_RULES_CSV), ('table batches', TABLE_BATCHES_JSON), ('evidence units', EVIDENCE_UNITS_JSON)]:\n"
        "    print(label + ':', path, path.exists())\n"
        "print('Output dir:', POST_DIR)"
    ),
    md("## Load Existing Outputs"),
    code(
        "table_raw_df = pd.read_csv(TABLE_RULES_CSV)\n"
        "non_table_raw_df = pd.read_csv(NON_TABLE_RULES_CSV)\n"
        "table_batches = json.loads(TABLE_BATCHES_JSON.read_text(encoding='utf-8'))\n"
        "evidence_units = json.loads(EVIDENCE_UNITS_JSON.read_text(encoding='utf-8'))\n\n"
        "table_evidence_lookup = {}\n"
        "batch_lookup = {}\n"
        "for batch in table_batches:\n"
        "    for row in batch.get('rows', []):\n"
        "        eid = row.get('evidence_id')\n"
        "        if eid:\n"
        "            table_evidence_lookup[eid] = row\n"
        "            batch_lookup[eid] = batch\n"
        "evidence_lookup = {ev.get('evidence_id'): ev for ev in evidence_units if ev.get('evidence_id')}\n\n"
        "print('table raw rules:', len(table_raw_df))\n"
        "print('non-table raw rules:', len(non_table_raw_df))\n"
        "print('table evidence rows:', len(table_evidence_lookup))\n"
        "print('all evidence units:', len(evidence_lookup))"
    ),
    md("## Shared Helpers"),
    code(
        "def is_blank(value):\n"
        "    if value is None:\n"
        "        return True\n"
        "    try:\n"
        "        if pd.isna(value):\n"
        "            return True\n"
        "    except Exception:\n"
        "        pass\n"
        "    return str(value).strip() == ''\n\n"
        "def clean(value):\n"
        "    return '' if is_blank(value) else str(value).strip()\n\n"
        "def norm(value):\n"
        "    return re.sub(r'\\s+', ' ', clean(value).lower()).strip()\n\n"
        "def numeric_value(value):\n"
        "    text = clean(value).replace(',', '')\n"
        "    m = re.search(r'-?\\d+(?:\\.\\d+)?', text)\n"
        "    return m.group(0) if m else text\n\n"
        "def normalize_unit_any(unit):\n"
        "    u = norm(unit)\n"
        "    if u in {'%', 'percent', 'percentage'}:\n"
        "        return 'percent'\n"
        "    if u in {'m', 'meter', 'meters', 'metre', 'metres'}:\n"
        "        return 'm'\n"
        "    if u in {'sq. m', 'sq m', 'm2', 'square metre', 'square metres', 'square meter', 'square meters'}:\n"
        "        return 'sq. m'\n"
        "    if 'storey' in u or 'story' in u:\n"
        "        return 'storeys'\n"
        "    if 'unit' in u:\n"
        "        return 'units'\n"
        "    return u\n\n"
        "def evidence_text_for(rule):\n"
        "    eid = clean(rule.get('evidence_id'))\n"
        "    if eid in table_evidence_lookup:\n"
        "        return table_evidence_lookup[eid].get('text', '')\n"
        "    return evidence_lookup.get(eid, {}).get('text', '')\n"
    ),
    md("## Table Rule Normalization"),
    code(
        "def infer_height_subject(evidence_id, row_label, value, unit, condition):\n"
        "    text = norm(table_evidence_lookup.get(evidence_id, {}).get('text', ''))\n"
        "    row = norm(row_label)\n"
        "    val = numeric_value(value)\n"
        "    if 'accessory' in row or 'accessory' in text:\n"
        "        return 'accessory_building'\n"
        "    if val in {'10', '10.0', '9.5', '3', '3.0', '2.5'} and evidence_id.endswith(('row_001', 'row_002')):\n"
        "        return 'front_principal_building'\n"
        "    if val in {'7.5', '7.0', '2', '2.0'} and evidence_id.endswith(('row_004', 'row_005')):\n"
        "        return 'rear_principal_building'\n"
        "    if val in {'10', '10.0', '9.5'}:\n"
        "        return 'front_principal_building'\n"
        "    if val in {'7.5', '7.0'}:\n"
        "        return 'rear_principal_building'\n"
        "    return 'building'\n\n"
        "def normalize_table_key(rule):\n"
        "    group = norm(rule.get('group_title'))\n"
        "    row = norm(rule.get('row_label'))\n"
        "    unit = normalize_unit_any(rule.get('unit'))\n"
        "    value = numeric_value(rule.get('value'))\n"
        "    condition = norm(rule.get('condition'))\n"
        "    eid = clean(rule.get('evidence_id'))\n"
        "    if 'permitted dwelling units' in row:\n"
        "        return 'permitted_dwelling_units'\n"
        "    if 'minimum lot area' in row:\n"
        "        return 'min_lot_area'\n"
        "    if 'maximum lot area' in row:\n"
        "        return 'max_lot_area'\n"
        "    if 'lot coverage' in group and 'impervious' in row:\n"
        "        return 'max_impervious_surface'\n"
        "    if 'lot coverage' in group:\n"
        "        return 'max_lot_coverage_all_buildings'\n"
        "    if group == 'height':\n"
        "        subject = infer_height_subject(eid, row, value, unit, condition)\n"
        "        if unit == 'storeys':\n"
        "            return f'max_{subject}_storeys'\n"
        "        if 'flat' in condition:\n"
        "            return f'max_{subject}_height_flat_roof'\n"
        "        if 'sloping' in condition or 'sloped' in condition:\n"
        "            return f'max_{subject}_height_sloped_roof'\n"
        "        return f'max_{subject}_height'\n"
        "    if 'setback' in group or 'yard' in row:\n"
        "        if 'street yard' in row:\n"
        "            return 'min_street_yard_setback'\n"
        "        if 'lane yard' in row:\n"
        "            return 'min_lane_yard_setback'\n"
        "        if 'interior rear' in row:\n"
        "            return 'min_interior_rear_yard_setback'\n"
        "        if 'interior side' in row:\n"
        "            return 'min_interior_side_yard_setback'\n"
        "    if 'between' in group or 'between' in row:\n"
        "        if 'front & rear' in row or 'front and rear' in row:\n"
        "            return 'min_separation_between_front_and_rear_principals'\n"
        "        if 'rear principals' in row:\n"
        "            return 'min_separation_between_rear_principals'\n"
        "        if 'front principals' in row:\n"
        "            return 'min_separation_between_front_principals'\n"
        "        if 'all other buildings' in row:\n"
        "            return 'min_separation_between_all_other_buildings'\n"
        "    return re.sub(r'[^a-z0-9]+', '_', norm(rule.get('rule_key_suggestion') or rule.get('rule_key'))).strip('_') or 'unknown_rule'\n\n"
        "def normalize_table_operator(rule):\n"
        "    key = clean(rule.get('normalized_rule_key'))\n"
        "    group = norm(rule.get('group_title'))\n"
        "    op = clean(rule.get('operator'))\n"
        "    if 'maximum' in group or key.startswith('max_'):\n"
        "        return '<='\n"
        "    if 'minimum' in group or key.startswith('min_'):\n"
        "        return '>='\n"
        "    return op if op in {'<=', '>=', '='} else '='\n\n"
        "def normalize_table_rule(row):\n"
        "    rule = row.to_dict()\n"
        "    rule['source_stream'] = 'table'\n"
        "    rule['evidence_text'] = evidence_text_for(rule)\n"
        "    rule['value'] = numeric_value(rule.get('value'))\n"
        "    rule['unit'] = normalize_unit_any(rule.get('unit'))\n"
        "    rule['condition'] = clean(rule.get('condition'))\n"
        "    rule['exception'] = clean(rule.get('exception'))\n"
        "    rule['normalized_rule_key'] = normalize_table_key(rule)\n"
        "    rule['operator'] = normalize_table_operator(rule)\n"
        "    return rule\n"
    ),
    md("## Non-Table Rule Normalization"),
    code(
        "def normalize_non_table_key(rule):\n"
        "    text = norm(' '.join(clean(rule.get(k)) for k in ['rule_key','rule_object','subject','condition','value']))\n"
        "    ev_text = norm(evidence_text_for(rule))\n"
        "    hay = text + ' ' + ev_text\n"
        "    if 'sprinkler' in hay:\n"
        "        return 'required_automatic_sprinkler_system'\n"
        "    if 'walkway_clear_height' in text or 'clear_height' in text:\n"
        "        return 'min_clear_height'\n"
        "    if 'walkway' in hay and ('wide' in hay or '1.5' in hay):\n"
        "        return 'min_pedestrian_walkway_width'\n"
        "    if 'walkway' in hay and ('spaced' in hay or '100' in hay):\n"
        "        return 'max_pedestrian_walkway_spacing'\n"
        "    if 'panhandle_width' in text:\n"
        "        return 'min_panhandle_width'\n"
        "    if 'panhandle_clearance_height' in text or ('panhandle' in hay and 'clear to a height' in hay):\n"
        "        return 'min_clear_height'\n"
        "    if 'panhandle' in hay and 'width' in hay:\n"
        "        return 'min_panhandle_width'\n"
        "    if 'fire access corridor' in hay and ('width' in hay or '1.0' in hay):\n"
        "        return 'min_fire_access_corridor_width'\n"
        "    if 'clear' in hay and 'height' in hay:\n"
        "        return 'min_clear_height'\n"
        "    if 'main entrance' in hay:\n"
        "        return 'required_main_entrance_orientation'\n"
        "    if 'floor area' in hay:\n"
        "        return 'min_floor_area'\n"
        "    if 'impervious_surface' in text or 'impervious surface area' in text:\n"
        "        return 'max_impervious_surface_exception'\n"
        "    if 'lot_coverage' in text or 'lot coverage' in hay:\n"
        "        return 'max_lot_coverage_exception'\n"
        "    if 'street yard' in hay and ('setback' in hay or '2.0' in hay):\n"
        "        return 'min_street_yard_setback_exception'\n"
        "    if 'parking' in hay and 'not required' in hay:\n"
        "        return 'not_required_off_street_parking'\n"
        "    if 'parking' in hay:\n"
        "        return 'parking_location_permission'\n"
        "    if 'side_lot_line' in text:\n"
        "        return 'min_separation_between_other_principals'\n"
        "    if 'through_lots' in text or text.strip() == 'principal_building_separation' or 'opposing front principals' in hay:\n"
        "        return 'min_separation_between_front_and_rear_principals'\n"
        "    if 'any other principals' in hay:\n"
        "        return 'min_separation_between_other_principals'\n"
        "    if 'separation' in hay and '2.4' in hay:\n"
        "        return 'min_separation_between_other_principals'\n"
        "    if 'separation' in hay and '6.0' in hay:\n"
        "        return 'min_separation_between_front_and_rear_principals'\n"
        "    return re.sub(r'[^a-z0-9]+', '_', clean(rule.get('rule_key'))).strip('_') or 'unknown_rule'\n\n"
        "def normalize_non_table_rule(row):\n"
        "    rule = row.to_dict()\n"
        "    rule['source_stream'] = 'non_table'\n"
        "    rule['evidence_text'] = evidence_text_for(rule)\n"
        "    # Fix a few common Gemini placements before keying.\n"
        "    hay = norm(' '.join(clean(rule.get(k)) for k in ['rule_key','rule_object','subject','condition','value']) + ' ' + rule['evidence_text'])\n"
        "    if 'sprinkler' in hay and is_blank(rule.get('value')):\n"
        "        m = re.search(r'(\\d+(?:\\.\\d+)?)\\s*m', hay)\n"
        "        if m:\n"
        "            rule['value'] = m.group(1)\n"
        "            rule['unit'] = 'm'\n"
        "            rule['operator'] = '>'\n"
        "    if 'not required' in hay:\n"
        "        rule['value'] = 'not required'\n"
        "        rule['operator'] = '='\n"
        "        rule['unit'] = ''\n"
        "    rule['value'] = numeric_value(rule.get('value'))\n"
        "    rule['unit'] = normalize_unit_any(rule.get('unit'))\n"
        "    rule['condition'] = clean(rule.get('condition'))\n"
        "    rule['exception'] = clean(rule.get('exception'))\n"
        "    rule['normalized_rule_key'] = normalize_non_table_key(rule)\n"
        "    if clean(rule.get('operator')) not in {'<=', '>=', '=', '>'}:\n"
        "        if clean(rule.get('constraint_type')) in {'min', 'required'} and rule['value']:\n"
        "            rule['operator'] = '>='\n"
        "        elif clean(rule.get('constraint_type')) == 'max' and rule['value']:\n"
        "            rule['operator'] = '<='\n"
        "    return rule\n"
    ),
    md("## Normalize, Split Exceptions, Combine, Deduplicate"),
    code(
        "table_rules = [normalize_table_rule(row) for _, row in table_raw_df.iterrows()]\n"
        "non_table_rules = [normalize_non_table_rule(row) for _, row in non_table_raw_df.iterrows()]\n\n"
        "def split_exception_rule(rule):\n"
        "    out = [rule]\n"
        "    exc = norm(rule.get('exception'))\n"
        "    if rule.get('normalized_rule_key') == 'min_interior_rear_yard_setback' and '1.5' in exc and 'accessory' in exc:\n"
        "        r = dict(rule)\n"
        "        r['value'] = '1.5'\n"
        "        r['unit'] = 'm'\n"
        "        r['condition'] = 'accessory buildings'\n"
        "        r['exception'] = ''\n"
        "        r['postprocess_source'] = 'derived_from_table_exception'\n"
        "        out.append(r)\n"
        "    return out\n\n"
        "expanded = []\n"
        "for rule in table_rules + non_table_rules:\n"
        "    expanded.extend(split_exception_rule(rule))\n"
        "combined_df = pd.DataFrame(expanded)\n\n"
        "def final_action(rule):\n"
        "    ev_text = norm(rule.get('evidence_text'))\n"
        "    if any(w in ev_text for w in ['may', 'subject to', 'provided that', 'except', 'director']):\n"
        "        return 'REVIEW'\n"
        "    return 'ACCEPT'\n\n"
        "combined_df['final_action'] = combined_df.apply(final_action, axis=1)\n"
        "combined_df['value_visible'] = combined_df.apply(lambda r: value_visible_in_evidence(r.to_dict(), r.get('evidence_text', '')), axis=1)\n"
        "combined_df['dedup_key'] = combined_df.apply(lambda r: '|'.join(norm(r.get(c)) for c in ['evidence_id','normalized_rule_key','operator','value','unit','condition','exception']), axis=1)\n"
        "deduped_df = combined_df.drop_duplicates('dedup_key', keep='first').reset_index(drop=True)\n\n"
        "print('table raw:', len(table_raw_df), '-> normalized:', len(table_rules))\n"
        "print('non-table raw:', len(non_table_raw_df), '-> normalized:', len(non_table_rules))\n"
        "print('combined expanded:', len(combined_df))\n"
        "print('deduped:', len(deduped_df))\n"
        "display(deduped_df[['source_stream','normalized_rule_key','operator','value','unit','condition','exception','final_action','value_visible','evidence_id']].head(120))"
    ),
    md("## Coverage Check"),
    code(
        "expected_keys = [\n"
        "    'permitted_dwelling_units', 'min_lot_area', 'max_lot_area',\n"
        "    'max_lot_coverage_all_buildings', 'max_impervious_surface',\n"
        "    'max_front_principal_building_height_sloped_roof', 'max_front_principal_building_height_flat_roof', 'max_front_principal_building_storeys',\n"
        "    'max_rear_principal_building_height_sloped_roof', 'max_rear_principal_building_height_flat_roof', 'max_rear_principal_building_storeys',\n"
        "    'max_accessory_building_height', 'max_accessory_building_storeys',\n"
        "    'min_street_yard_setback', 'min_lane_yard_setback', 'min_interior_rear_yard_setback', 'min_interior_side_yard_setback',\n"
        "    'min_separation_between_front_principals', 'min_separation_between_rear_principals', 'min_separation_between_front_and_rear_principals', 'min_separation_between_all_other_buildings',\n"
        "    'required_main_entrance_orientation', 'max_pedestrian_walkway_spacing', 'min_pedestrian_walkway_width', 'min_clear_height',\n"
        "    'min_floor_area', 'required_automatic_sprinkler_system', 'min_fire_access_corridor_width', 'min_panhandle_width',\n"
        "    'max_lot_coverage_exception', 'max_impervious_surface_exception', 'min_street_yard_setback_exception', 'not_required_off_street_parking',\n"
        "]\n"
        "found = set(deduped_df['normalized_rule_key'])\n"
        "coverage_df = pd.DataFrame([{'expected_key': key, 'found': key in found} for key in expected_keys])\n"
        "display(coverage_df)\n"
        "print('Expected keys found:', int(coverage_df['found'].sum()), '/', len(coverage_df))\n"
        "print('\\nCounts by stream:')\n"
        "print(deduped_df['source_stream'].value_counts().to_string())\n"
        "print('\\nCounts by final action:')\n"
        "print(deduped_df['final_action'].value_counts().to_string())\n"
        "print('\\nCounts by key:')\n"
        "print(deduped_df['normalized_rule_key'].value_counts().sort_index().to_string())"
    ),
    md("## Save Hybrid Outputs"),
    code(
        "combined_path = POST_DIR / 'gemini_hybrid_rules_postprocessed.csv'\n"
        "combined_json_path = POST_DIR / 'gemini_hybrid_rules_postprocessed.json'\n"
        "deduped_path = POST_DIR / 'gemini_hybrid_rules_postprocessed_deduped.csv'\n"
        "deduped_json_path = POST_DIR / 'gemini_hybrid_rules_postprocessed_deduped.json'\n"
        "accepted_path = POST_DIR / 'gemini_hybrid_accepted_rules.csv'\n"
        "review_path = POST_DIR / 'gemini_hybrid_review_rules.csv'\n"
        "coverage_path = POST_DIR / 'gemini_hybrid_expected_key_coverage.csv'\n"
        "summary_path = POST_DIR / 'gemini_hybrid_postprocess_summary.md'\n\n"
        "combined_df.to_csv(combined_path, index=False, encoding='utf-8-sig')\n"
        "combined_json_path.write_text(combined_df.to_json(orient='records', force_ascii=False, indent=2), encoding='utf-8')\n"
        "deduped_df.to_csv(deduped_path, index=False, encoding='utf-8-sig')\n"
        "deduped_json_path.write_text(deduped_df.to_json(orient='records', force_ascii=False, indent=2), encoding='utf-8')\n"
        "deduped_df[deduped_df['final_action'] == 'ACCEPT'].to_csv(accepted_path, index=False, encoding='utf-8-sig')\n"
        "deduped_df[deduped_df['final_action'] == 'REVIEW'].to_csv(review_path, index=False, encoding='utf-8-sig')\n"
        "coverage_df.to_csv(coverage_path, index=False, encoding='utf-8-sig')\n\n"
        "summary_lines = [\n"
        "    '# Gemini Hybrid Postprocess Summary', '',\n"
        "    f'table_raw_rules: {len(table_raw_df)}',\n"
        "    f'non_table_raw_rules: {len(non_table_raw_df)}',\n"
        "    f'combined_expanded_rules: {len(combined_df)}',\n"
        "    f'deduped_rules: {len(deduped_df)}',\n"
        "    f'accepted_rules: {int((deduped_df[\"final_action\"] == \"ACCEPT\").sum())}',\n"
        "    f'review_rules: {int((deduped_df[\"final_action\"] == \"REVIEW\").sum())}',\n"
        "    f'expected_keys_found: {int(coverage_df[\"found\"].sum())}/{len(coverage_df)}',\n"
        "    '', '## Counts By Stream', deduped_df['source_stream'].value_counts().to_string(),\n"
        "    '', '## Counts By Key', deduped_df['normalized_rule_key'].value_counts().sort_index().to_string(),\n"
        "]\n"
        "summary_path.write_text('\\n'.join(summary_lines), encoding='utf-8')\n\n"
        "print('Saved:', POST_DIR)\n"
        "print('\\n' + summary_path.read_text(encoding='utf-8'))"
    ),
]

nbf.write(nb, OUT)
print(f"Wrote {OUT}")
