import nbformat as nbf
from pathlib import Path


OUT = Path(__file__).with_name("gemini_table_postprocess_probe.ipynb")


def md(text):
    return nbf.v4.new_markdown_cell(text)


def code(text):
    return nbf.v4.new_code_cell(text)


nb = nbf.v4.new_notebook()
nb["metadata"] = {
    "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
    "language_info": {"name": "python", "pygments_lexer": "ipython3"},
}

nb.cells = [
    md(
        "# Gemini Table Postprocess Probe - Burnaby R1\n\n"
        "Offline-only notebook. It reads the existing Gemini table extraction output and tests deterministic post-processing.\n\n"
        "No Gemini/API calls are made here."
    ),
    code(
        "import json\n"
        "import os\n"
        "import re\n"
        "from pathlib import Path\n\n"
        "import pandas as pd\n\n"
        "def locate_prototype_dir():\n"
        "    cwd = Path.cwd()\n"
        "    for d in [cwd, *cwd.parents]:\n"
        "        candidate = d / 'code' / 'prototype_pipeline'\n"
        "        if (candidate / 'prototype_rule_extraction_pipeline.ipynb').exists():\n"
        "            return candidate.resolve()\n"
        "        if (d / 'prototype_rule_extraction_pipeline.ipynb').exists():\n"
        "            return d.resolve()\n"
        "    return cwd.resolve()\n\n"
        "PROTOTYPE_DIR = locate_prototype_dir()\n"
        "os.chdir(PROTOTYPE_DIR)\n\n"
        "import sys\n"
        "import importlib\n"
        "if str(PROTOTYPE_DIR) not in sys.path:\n"
        "    sys.path.insert(0, str(PROTOTYPE_DIR))\n"
        "import prototype_target_aware_helpers as helpers\n"
        "importlib.reload(helpers)\n"
        "from prototype_target_aware_helpers import *\n\n"
        "print('PROTOTYPE_DIR:', PROTOTYPE_DIR)"
    ),
    md("## Paths"),
    code(
        "TARGET_CITY = 'burnaby'\n"
        "RUN_ID = f'prototype_{TARGET_CITY}_rule_pipeline'\n"
        "RULE_DIR = PROTOTYPE_DIR / 'outputs' / TARGET_CITY / RUN_ID / '03_rules'\n"
        "GEMINI_DIR = PROTOTYPE_DIR / 'outputs' / TARGET_CITY / RUN_ID / '04_gemini_table_probe'\n"
        "POST_DIR = PROTOTYPE_DIR / 'outputs' / TARGET_CITY / RUN_ID / '05_gemini_table_postprocess_probe'\n"
        "POST_DIR.mkdir(parents=True, exist_ok=True)\n\n"
        "GEMINI_RULES_CSV = GEMINI_DIR / 'gemini_table_rules.csv'\n"
        "TABLE_BATCHES_JSON = RULE_DIR / 'table_rule_batches.json'\n\n"
        "print('Gemini rules:', GEMINI_RULES_CSV, GEMINI_RULES_CSV.exists())\n"
        "print('Table batches:', TABLE_BATCHES_JSON, TABLE_BATCHES_JSON.exists())\n"
        "print('Output dir:', POST_DIR)"
    ),
    md("## Load Existing Gemini Output"),
    code(
        "raw_rules_df = pd.read_csv(GEMINI_RULES_CSV)\n"
        "table_batches = json.loads(TABLE_BATCHES_JSON.read_text(encoding='utf-8'))\n\n"
        "evidence_lookup = {}\n"
        "batch_lookup = {}\n"
        "for batch in table_batches:\n"
        "    for row in batch.get('rows', []):\n"
        "        eid = row.get('evidence_id')\n"
        "        if eid:\n"
        "            evidence_lookup[eid] = row\n"
        "            batch_lookup[eid] = batch\n\n"
        "print('Raw Gemini rules:', len(raw_rules_df))\n"
        "print('Evidence rows:', len(evidence_lookup))\n"
        "display(raw_rules_df[['group_title','row_label','rule_key_suggestion','operator','value','unit','condition','exception']].head(80))"
    ),
    md("## Deterministic Normalization Helpers"),
    code(
        "def is_blank(value):\n"
        "    if value is None:\n"
        "        return True\n"
        "    try:\n"
        "        if pd.isna(value):\n"
        "            return True\n"
        "    except Exception:\n"
        "        pass\n"
        "    return str(value).strip() == ''\n\n"
        "def clean(value):\n"
        "    return '' if is_blank(value) else str(value).strip()\n\n"
        "def norm(value):\n"
        "    return re.sub(r'\\s+', ' ', clean(value).lower()).strip()\n\n"
        "def numeric_value(value):\n"
        "    text = clean(value).replace(',', '')\n"
        "    m = re.search(r'-?\\d+(?:\\.\\d+)?', text)\n"
        "    return m.group(0) if m else text\n\n"
        "def normalize_unit(unit):\n"
        "    u = norm(unit)\n"
        "    if u in {'%', 'percent', 'percentage'}:\n"
        "        return 'percent'\n"
        "    if u in {'m', 'meter', 'meters', 'metre', 'metres'}:\n"
        "        return 'm'\n"
        "    if u in {'sq. m', 'sq m', 'm2', 'square metre', 'square metres', 'square meter', 'square meters'}:\n"
        "        return 'sq. m'\n"
        "    if 'storey' in u or 'story' in u:\n"
        "        return 'storeys'\n"
        "    if 'unit' in u:\n"
        "        return 'units'\n"
        "    return u\n\n"
        "def infer_height_subject(evidence_id, row_label, value, unit, condition):\n"
        "    text = norm(evidence_lookup.get(evidence_id, {}).get('text', ''))\n"
        "    row = norm(row_label)\n"
        "    val = numeric_value(value)\n"
        "    cond = norm(condition)\n"
        "    if 'accessory' in row or 'accessory' in text:\n"
        "        return 'accessory_building'\n"
        "    if val in {'10', '10.0', '9.5', '3', '3.0', '2.5'} and evidence_id.endswith(('row_001', 'row_002')):\n"
        "        return 'front_principal_building'\n"
        "    if val in {'7.5', '7.0', '2', '2.0'} and evidence_id.endswith(('row_004', 'row_005')):\n"
        "        return 'rear_principal_building'\n"
        "    if val in {'10', '10.0', '9.5'}:\n"
        "        return 'front_principal_building'\n"
        "    if val in {'7.5', '7.0'}:\n"
        "        return 'rear_principal_building'\n"
        "    return 'building'\n\n"
        "def normalize_rule_key_offline(rule):\n"
        "    group = norm(rule.get('group_title'))\n"
        "    row = norm(rule.get('row_label'))\n"
        "    unit = normalize_unit(rule.get('unit'))\n"
        "    value = numeric_value(rule.get('value'))\n"
        "    condition = norm(rule.get('condition'))\n"
        "    eid = clean(rule.get('evidence_id'))\n\n"
        "    if 'permitted dwelling units' in row:\n"
        "        return 'permitted_dwelling_units'\n"
        "    if 'minimum lot area' in row:\n"
        "        return 'min_lot_area'\n"
        "    if 'maximum lot area' in row:\n"
        "        return 'max_lot_area'\n"
        "    if 'lot coverage' in group and 'impervious' in row:\n"
        "        return 'max_impervious_surface'\n"
        "    if 'lot coverage' in group:\n"
        "        return 'max_lot_coverage_all_buildings'\n"
        "    if group == 'height':\n"
        "        subject = infer_height_subject(eid, row, value, unit, condition)\n"
        "        if unit == 'storeys':\n"
        "            return f'max_{subject}_storeys'\n"
        "        if 'flat' in condition:\n"
        "            return f'max_{subject}_height_flat_roof'\n"
        "        if 'sloping' in condition or 'sloped' in condition:\n"
        "            return f'max_{subject}_height_sloped_roof'\n"
        "        return f'max_{subject}_height'\n"
        "    if 'setback' in group or 'yard' in row:\n"
        "        if 'street yard' in row:\n"
        "            return 'min_street_yard_setback'\n"
        "        if 'lane yard' in row:\n"
        "            return 'min_lane_yard_setback'\n"
        "        if 'interior rear' in row:\n"
        "            return 'min_interior_rear_yard_setback'\n"
        "        if 'interior side' in row:\n"
        "            return 'min_interior_side_yard_setback'\n"
        "    if 'between' in group or 'between' in row:\n"
        "        if 'front & rear' in row or 'front and rear' in row:\n"
        "            return 'min_separation_between_front_and_rear_principals'\n"
        "        if 'rear principals' in row:\n"
        "            return 'min_separation_between_rear_principals'\n"
        "        if 'front principals' in row:\n"
        "            return 'min_separation_between_front_principals'\n"
        "        if 'all other buildings' in row:\n"
        "            return 'min_separation_between_all_other_buildings'\n"
        "    return re.sub(r'[^a-z0-9]+', '_', norm(rule.get('rule_key_suggestion'))).strip('_') or 'unknown_rule'\n\n"
        "def normalize_operator_offline(rule):\n"
        "    op = clean(rule.get('operator'))\n"
        "    group = norm(rule.get('group_title'))\n"
        "    key = clean(rule.get('normalized_rule_key'))\n"
        "    if 'maximum' in group or key.startswith('max_'):\n"
        "        return '<='\n"
        "    if 'minimum' in group or key.startswith('min_'):\n"
        "        return '>='\n"
        "    if op in {'<=', '>=', '='}:\n"
        "        return op\n"
        "    return '='"
    ),
    md("## Normalize, Split Exceptions, Deduplicate"),
    code(
        "def normalize_one(row):\n"
        "    rule = row.to_dict()\n"
        "    eid = clean(rule.get('evidence_id'))\n"
        "    ev = evidence_lookup.get(eid, {})\n"
        "    rule['evidence_text'] = ev.get('text', rule.get('value_source_text', ''))\n"
        "    rule['value'] = numeric_value(rule.get('value'))\n"
        "    rule['unit'] = normalize_unit(rule.get('unit'))\n"
        "    rule['condition'] = clean(rule.get('condition'))\n"
        "    rule['exception'] = clean(rule.get('exception'))\n"
        "    rule['normalized_rule_key'] = normalize_rule_key_offline(rule)\n"
        "    rule['operator'] = normalize_operator_offline(rule)\n"
        "    rule['postprocess_source'] = 'gemini_existing_output'\n"
        "    return rule\n\n"
        "normalized_rules = [normalize_one(row) for _, row in raw_rules_df.iterrows()]\n\n"
        "def split_exception_rule(rule):\n"
        "    out = [rule]\n"
        "    exc = norm(rule.get('exception'))\n"
        "    if rule.get('normalized_rule_key') == 'min_interior_rear_yard_setback' and '1.5' in exc and 'accessory' in exc:\n"
        "        r = dict(rule)\n"
        "        r['value'] = '1.5'\n"
        "        r['unit'] = 'm'\n"
        "        r['condition'] = 'accessory buildings'\n"
        "        r['exception'] = ''\n"
        "        r['postprocess_source'] = 'derived_from_exception'\n"
        "        out.append(r)\n"
        "    return out\n\n"
        "expanded_rules = []\n"
        "for rule in normalized_rules:\n"
        "    expanded_rules.extend(split_exception_rule(rule))\n\n"
        "processed_df = pd.DataFrame(expanded_rules)\n\n"
        "def dedup_key(row):\n"
        "    parts = [\n"
        "        row.get('evidence_id'), row.get('normalized_rule_key'), row.get('operator'),\n"
        "        numeric_value(row.get('value')), normalize_unit(row.get('unit')),\n"
        "        norm(row.get('condition')), norm(row.get('exception')),\n"
        "    ]\n"
        "    return '|'.join(clean(p).lower() for p in parts)\n\n"
        "processed_df['dedup_key'] = processed_df.apply(dedup_key, axis=1)\n"
        "deduped_df = processed_df.drop_duplicates('dedup_key', keep='first').reset_index(drop=True)\n\n"
        "print('Raw Gemini rules:', len(raw_rules_df))\n"
        "print('After exception split:', len(processed_df))\n"
        "print('Deduped:', len(deduped_df))\n"
        "display(deduped_df[['group_title','row_label','normalized_rule_key','operator','value','unit','condition','exception','postprocess_source']])"
    ),
    md("## Coverage-Oriented Quality Check"),
    code(
        "expected_groups = {\n"
        "    'Development Regulations': ['permitted_dwelling_units', 'min_lot_area', 'max_lot_area'],\n"
        "    'Maximum Lot Coverage': ['max_lot_coverage_all_buildings', 'max_impervious_surface'],\n"
        "    'Height': [\n"
        "        'max_front_principal_building_height_sloped_roof', 'max_front_principal_building_height_flat_roof',\n"
        "        'max_front_principal_building_storeys', 'max_rear_principal_building_height_sloped_roof',\n"
        "        'max_rear_principal_building_height_flat_roof', 'max_rear_principal_building_storeys',\n"
        "        'max_accessory_building_height', 'max_accessory_building_storeys',\n"
        "    ],\n"
        "    'Minimum Lot Line Setbacks': [\n"
        "        'min_street_yard_setback', 'min_lane_yard_setback',\n"
        "        'min_interior_rear_yard_setback', 'min_interior_side_yard_setback',\n"
        "    ],\n"
        "    'Minimum Separation': [\n"
        "        'min_separation_between_front_principals', 'min_separation_between_rear_principals',\n"
        "        'min_separation_between_front_and_rear_principals', 'min_separation_between_all_other_buildings',\n"
        "    ],\n"
        "}\n\n"
        "found_keys = set(deduped_df['normalized_rule_key'])\n"
        "coverage_rows = []\n"
        "for group, keys in expected_groups.items():\n"
        "    for key in keys:\n"
        "        coverage_rows.append({'group': group, 'expected_key': key, 'found': key in found_keys})\n"
        "coverage_df = pd.DataFrame(coverage_rows)\n\n"
        "display(coverage_df)\n"
        "print('Expected keys found:', int(coverage_df['found'].sum()), '/', len(coverage_df))\n"
        "print('\\nRule counts by normalized key:')\n"
        "print(deduped_df['normalized_rule_key'].value_counts().sort_index().to_string())"
    ),
    md("## Save Offline Postprocess Outputs"),
    code(
        "processed_path = POST_DIR / 'gemini_table_rules_postprocessed.csv'\n"
        "processed_json_path = POST_DIR / 'gemini_table_rules_postprocessed.json'\n"
        "deduped_path = POST_DIR / 'gemini_table_rules_postprocessed_deduped.csv'\n"
        "deduped_json_path = POST_DIR / 'gemini_table_rules_postprocessed_deduped.json'\n"
        "coverage_path = POST_DIR / 'gemini_table_postprocess_coverage.csv'\n"
        "summary_path = POST_DIR / 'gemini_table_postprocess_summary.md'\n\n"
        "processed_df.to_csv(processed_path, index=False, encoding='utf-8-sig')\n"
        "processed_json_path.write_text(processed_df.to_json(orient='records', force_ascii=False, indent=2), encoding='utf-8')\n"
        "deduped_df.to_csv(deduped_path, index=False, encoding='utf-8-sig')\n"
        "deduped_json_path.write_text(deduped_df.to_json(orient='records', force_ascii=False, indent=2), encoding='utf-8')\n"
        "coverage_df.to_csv(coverage_path, index=False, encoding='utf-8-sig')\n\n"
        "summary_lines = [\n"
        "    '# Gemini Table Postprocess Summary', '',\n"
        "    f'raw_gemini_rules: {len(raw_rules_df)}',\n"
        "    f'after_exception_split: {len(processed_df)}',\n"
        "    f'deduped_rules: {len(deduped_df)}',\n"
        "    f'expected_keys_found: {int(coverage_df[\"found\"].sum())}/{len(coverage_df)}',\n"
        "    '', '## Counts By Key',\n"
        "    deduped_df['normalized_rule_key'].value_counts().sort_index().to_string(),\n"
        "]\n"
        "summary_path.write_text('\\n'.join(summary_lines), encoding='utf-8')\n\n"
        "print('Saved:', processed_path)\n"
        "print('Saved:', deduped_path)\n"
        "print('Saved:', coverage_path)\n"
        "print('\\n' + summary_path.read_text(encoding='utf-8'))"
    ),
]

nbf.write(nb, OUT)
print(f"Wrote {OUT}")
